apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: my-app
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: test
      template:
        metadata:
          labels:
            app: test
        spec:
          containers:
          - name: test
            image: test
            ports:
            - containerPort: 8080
