apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: my-sab
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: '${APP_NAME}'
      name: '${APP_NAME}'
    spec:
      ports:
        - port: 8080
          targetPort: 8080
      selector:
        deployment: '${APP_NAME}'
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: '${APP_NAME}'
      labels:
        app: '${APP_NAME}'
    spec:
      port:
        targetPort: http
      tls:
        insecureEdgeTerminationPolicy: '${ROUTE_INSECURE_EDGE}'
        termination: edge
      to:
        kind: Service
        name: '${APP_NAME}'
        weight: 100
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: '${APP_NAME}'
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: '${APP_NAME}'
      template:
        metadata:
          labels:
            app: '${APP_NAME}'
        spec:
          containers:
          - name: '${APP_NAME}'
            image: '${IMAGE}'
            env:
              - name: APP_USER
                value: '${APP_NAME}'
              - name: APP_PASS
                value: '${APP_NAME}'
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
            ports:
              - containerPort: 8080
parameters:
  - name: APP_NAME
    value: my-app
  - name: IMAGE
    value: test2
  - name: ROUTE_INSECURE_EDGE
    value: 'Allow'
  - name: APP_USER
    value: '${APP_USER}'
  - name: APP_PASS
    value: '${APP_PASS}'
  
