apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: my-app
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
          - name: ${APP_NAME}
            image: ${IMAGE}
            ports:
            - containerPort: 8080
parameters:
  - name: APP_NAME
    value: "my-app"
  - name: IMAGE
    value: "my-image"

